FROM registry.access.redhat.com/ubi8:latest
RUN dnf install python3 -y && dnf clean all
RUN mkdir /opt/KuberNoid/
COPY * /opt/KuberNoid/
RUN sed -i '/engine\.startGame/i\                                var podlisterurl = "podlister.url";\n                                engine.preloadFile(podlisterurl);' /opt/KuberNoid/KuberNoid.html
RUN ln -s /opt/KuberNoid/KuberNoid.html /opt/KuberNoid/index.html
WORKDIR /opt/KuberNoid
RUN chown -R 1024 /opt/KuberNoid/
USER 1024
CMD ["python3", "-u", "-m", "http.server"]
