FROM docker.io/library/golang:latest
WORKDIR /go/src/github.com/mvazquezc/KuberNoid
COPY main.go .
COPY go.mod .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o podlister .

FROM scratch
COPY --from=0 /go/src/github.com/mvazquezc/KuberNoid/podlister .
USER 1024
EXPOSE 9000
ENTRYPOINT ["/podlister"]
